#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Exporter-Tidy
Version  : 0.08
Release  : 9
URL      : https://cpan.metacpan.org/authors/id/J/JU/JUERD/Exporter-Tidy-0.08.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/J/JU/JUERD/Exporter-Tidy-0.08.tar.gz
Summary  : 'Another way of exporting symbols'
Group    : Development/Tools
License  : 0BSD AAL AFL-1.1 AFL-1.2 AFL-2.0 AFL-2.1 AFL-3.0 AGPL-3.0 AGPL-3.0-only AGPL-3.0-or-later APL-1.0 APSL-1.0 APSL-1.1 APSL-1.2 APSL-2.0 Apache-1.1 Apache-2.0 Artistic-1.0 Artistic-1.0-Perl Artistic-1.0-cl8 Artistic-2.0 BSD-2-Clause BSD-2-Clause-Patent BSD-3-Clause BSD-3-Clause-LBNL BSL-1.0 CATOSL-1.1 CDDL-1.0 CECILL-2.1 CNRI-Python CPAL-1.0 CPL-1.0 CUA-OPL-1.0 ECL-1.0 ECL-2.0 EFL-1.0 EFL-2.0 EPL-1.0 EPL-2.0 EUDatagrid EUPL-1.1 EUPL-1.2 Entessa Fair Frameworx-1.0 GPL-2.0 GPL-2.0+ GPL-2.0-only GPL-2.0-with-GCC-exception GPL-2.0-with-autoconf-exception GPL-2.0-with-bison-exception GPL-2.0-with-classpath-exception GPL-2.0-with-font-exception GPL-3.0 GPL-3.0+ GPL-3.0-only GPL-3.0-or-later GPL-3.0-with-GCC-exception GPL-3.0-with-autoconf-exception HPND IPA IPL-1.0 ISC Intel LGPL-2.0 LGPL-2.0+ LGPL-2.0-only LGPL-2.0-or-later LGPL-2.1 LGPL-2.1+ LGPL-2.1-only LGPL-3.0 LGPL-3.0+ LGPL-3.0-only LGPL-3.0-or-later LPL-1.0 LPL-1.02 LPPL-1.3c LiLiQ-P-1.1 LiLiQ-R-1.1 LiLiQ-Rplus-1.1 MIT MPL-1.0 MPL-1.1 MPL-2.0 MPL-2.0-no-copyleft-exception MS-PL MS-RL MirOS Motosoto Multics NASA-1.3 NCSA NGPL NPOSL-3.0 NTP Naumen Nokia OCLC-2.0 OFL-1.1 OGTSL OSET-PL-2.1 OSL-1.0 OSL-2.0 OSL-2.1 OSL-3.0 PHP-3.0 PostgreSQL Python-2.0 QPL-1.0 RPL-1.1 RPL-1.5 RPSL-1.0 RSCPL SISSL SPL-1.0 SimPL-2.0 Sleepycat UPL-1.0 VSL-1.0 W3C WXwindows Watcom-1.0 Xnet ZPL-2.0 Zlib
Requires: perl-Exporter-Tidy-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
Exporter::Tidy
INSTALLATION
To install this module type the following:
perl Makefile.PL
make
make test
make install

%package dev
Summary: dev components for the perl-Exporter-Tidy package.
Group: Development
Provides: perl-Exporter-Tidy-devel = %{version}-%{release}
Requires: perl-Exporter-Tidy = %{version}-%{release}

%description dev
dev components for the perl-Exporter-Tidy package.


%package perl
Summary: perl components for the perl-Exporter-Tidy package.
Group: Default
Requires: perl-Exporter-Tidy = %{version}-%{release}

%description perl
perl components for the perl-Exporter-Tidy package.


%prep
%setup -q -n Exporter-Tidy-0.08
cd %{_builddir}/Exporter-Tidy-0.08

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Exporter::Tidy.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/Exporter/Tidy.pm
